export const shopActionTypes = {
    FETCH_COLLECTIONS_START: "FETCH_COLLECTIONS_START",
    FETCH_COLLECTIONS_SUCCESS: "FETCH_COLLECTIONS_SUCCESS",
    FETCH_COLLECTIONS_FAILURE: "FETCH_COLLECTIONS_FAILURE",
    SET_LOADING: "SET_LOADING",
    RESET_LOADING: "RESET_LOADING"
  };
  