export const userActionTypes = {
  GOOGLE_SIGN_IN_START: 'GOOGLE_SIGN_IN_START',
  SIGN_IN_SUCCESS: 'SIGN_IN_SUCCESS',
  SIGN_IN_FAILURE: 'SIGN_IN_FAILURE',
  EMAIL_SIGN_IN_START: 'EMAIL_SIGN_IN_START',
  USER_SIGN_UP_START: 'USER_SIGN_UP_START',
  USER_SIGN_UP_SUCCESS: 'USER_SIGN_UP_SUCCESS',
  USER_SIGN_UP_FAILURE: 'USER_SIGN_UP_FAILURE',
  GET_USER_ON_AUTH_STATE_CHANGE_START: 'GET_USER_ON_AUTH_STATE_CHANGE_START',
  SIGN_OUT_START: 'SIGN_OUT_START',
  SIGN_OUT_SUCCESS: 'SIGN_OUT_SUCCESS',
  SIGN_OUT_FAILURE: 'SIGN_OUT_FAILURE'
};

